type DropdownData = Record<string, string[]>;

export const dropdownConfigs: DropdownData = {
  sursa: [
    "Prieten(ă) de familie",
    "Coleg(ă) de muncă",
    "Coleg(ă) de studii",
    "Rudă",
    "Rudă a soţiei",
    "Cunoscut(ă) prin intermediul Soţiei/Soţului",
    "Hobbyuri comune",
    "Vecin(ă)",
    "Client (loc de muncă anterior)",
    "Partener(ă) de afaceri",
    "Alte surse",
  ],
  venit: [
    "Sub 1.800 lei",
    "1.800-2.500 lei",
    "2.500-3.500 lei",
    "3.500-5.000 lei",
    "peste 5.000 lei",
  ],
  varsta: [
    "Sub 25 ani",
    "25-30 ani",
    "30-40 ani",
    "40-55 ani",
    "55-65 ani",
    "peste 65 ani",
  ],
  ocupatie: [
    "IT",
    "Profesie tehnica",
    "Constructii",
    "Finante/banci",
    "Avocat/Jurist",
    "Vanzari",
    "Patron",
    "Manager",
    "Director",
    "Muncitor calificat",
    "Armata/Politie/SRI",
    "Servicii publice",
    "Administratie guvernam.",
    "Pensionar",
    "Cercetator",
    "Student",
    "Altele",
  ],
  stareCivila: ["Casatorit", "Celibatar", "Divortat", "Vaduv"],
  numarCopii: ["Fara copii", "Unu", "Doi", "3 sau mai multi"],
  deCandCunoscPersoana: ["Mai putin de 2 ani", "2-5 ani", "Mai mult de 5 ani"],
  catDeBineCunoscPersoana: ["Foarte bine", "Bine", "Putin"],
  frecventaIntalniriAnuala: [
    "De peste 5 ori",
    "3-5 ori",
    "1-2 ori",
    "Niciodata",
  ],
  infoContact: ["Usor", "Relativ usor", "Greu", "Probabil Imposibil"],
  esteFurnizorReferinte: ["Excelent", "Bun", "Slab"],
  status: ["Client", "Prospect", "Contract", "Inactiv", "Referință"],
};
